[package]
name = "my_counter"
version = "1.0.0"
authors = []

[addresses]
my_counter_addr='48a138b4c3228d1982d99142f72e9cd38cad4d77280c2f669abdd1c9ca084eaf'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
